const Product_data = [
    {
        image: "/images/Smartphone.png",
        name: "smart phone 5G",
        price: 66,
        slug: "Smartphone",
        rating: 5,
        inStock: 100,
        reviews: 12,
        featured: true,
        arrival: "false",
        category: "Mobile & Tablet",
        description: "Smartphone with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/Smarttv.png",
        name: "smart tv",
        price: 40,
        slug: "Smarttv",
        rating: 4.2,
        inStock: 0,
        reviews: 120,
        featured: true,
        arrival: "false",
        category: "TV & Smart Box",
        description: "Smarttv with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/Portablespeaker.png",
        name: "portable speaker",
        price: 72,
        slug: "Portablespeaker",
        rating: 5,
        inStock: 40,
        reviews: 19,
        featured: true,
        arrival: "false",
        category: "Microphone & Audio",
        description: "Portablespeaker with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/Wirelessmicrophone.png",
        name: "wireless microphone",
        price: 22,
        slug: "Wirelessmicrophone",
        rating: 4,
        inStock: 10,
        reviews: 20,
        featured: true,
        arrival: "false",
        category: "Microphone & Audio",
        description: "Wireless microphone with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/Smartwatch.png",
        name: "smart watch",
        price: 65,
        slug: "Smartwatch",
        rating: 5,
        inStock: 80,
        reviews: 18,
        featured: true,
        arrival: "false",
        category: "Smart Watch",
        description: "Smart watch with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/Camera.png",
        name: "camera HD",
        price: 82,
        slug: "Camera",
        rating: 5,
        inStock: 40,
        reviews: 100,
        featured: true,
        arrival: "false",
        category: "Camera",
        description: "Camera HD with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/Headset.png",
        name: "headset Hyper",
        price: 40,
        slug: "Headset",
        rating: 3,
        inStock: 50,
        reviews: 82,
        featured: false,
        arrival: "false",
        category: "Microphone & Audio",
        description: "Headset Hyper with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/AndroidTv.jpg",
        name: "android Tv",
        price: 500,
        slug: "AndroidTv",
        rating: 3,
        inStock: 50,
        reviews: 82,
        featured: false,
        arrival: "false",
        category: "TV & Smart Box",
        description: "Smarttv with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/DigitalWatch.jpg",
        name: "digital Watch",
        price: 100,
        slug: "DigitalWatch",
        rating: 5,
        inStock: 20,
        reviews: 62,
        featured: false,
        arrival: "false",
        category: "Smart Watch",
        description: "Smart watch with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/CameraHd.jpg",
        name: "canon Camera",
        price: 300,
        slug: "Canoncamera",
        rating: 5,
        inStock: 50,
        reviews: 92,
        featured: false,
        arrival: "false",
        category: "Camera",
        description: "Camera HD with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/bluetooth.jpg",
        name: "bluetooth",
        price: 20,
        slug: "Bluetooth",
        rating: 5,
        inStock: 50,
        reviews: 22,
        featured: false,
        arrival: "false",
        category: "Mobile & Tablet",
        description: "Mobile & Tablet with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/Realme.jpg",
        name: "realme",
        price: 20,
        slug: "Realme",
        rating: 5,
        inStock: 20,
        reviews: 22,
        featured: false,
        arrival: "false",
        category: "Mobile & Tablet",
        description: "Mobile & Tablet with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/macbookpro.jpg",
        name: "macbook pro",
        price: 2000,
        slug: "mackbookpro",
        rating: 5,
        inStock: 50,
        reviews: 98,
        featured: false,
        arrival: "true",
        category: "Computer & Laptop",
        description: "Computer & Laptop with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/smarttv2.jpg",
        name: "4k smart tv",
        price: 400,
        slug: "4ksmarttv",
        rating: 4,
        inStock: 20,
        reviews: 50,
        featured: false,
        arrival: "true",
        category: "TV & Smart Box",
        description: "TV & Smart Box with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    },
    {
        image: "/images/usbspeaker.jpg",
        name: "usb speaker portable",
        price: 400,
        slug: "usbspeaker",
        rating: 3,
        inStock: 22,
        reviews: 8,
        featured: false,
        arrival: "true",
        category: "Microphone & Audio",
        description: "Microphone & Audio with the new style, shockproof, clear voice reception that suitable for recording, online meeting, vlogging, and calling. Free casing with high-quality zipper.",
        button: "Add to cart"
    }
]

export default Product_data